#
name: Generate medias from Musescore files

on:
  workflow_dispatch:

jobs:
  generate-medias:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: read
    container:
      image: ghcr.io/soprodecarnaval/musicoteca:main
      options: --user root --workdir /app
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Create generator file
        shell: sh
        run: |
          find public/collection/ -type f -name "*.mscz" | jq -R -s 'split("\n") | map(select(.!="") | sub(".mscz";"") | {"in":"\(.).mscz", "out": [[ "\(.)_",".svg"],[ "\(.)_",".midi"],"\(.).midi","\(.).metajson"]})' > media-generation.json
          head media-generation.json
      - name: Create media files
        shell: sh
        run: |
          xvfb-run /squashfs-root/AppRun -j media-generation.json
          find public/collection/ -type f -name "*.svg" -a -name "*.midi" | head
      - name: Commit and push files
        shell: sh
        run: |
          git config --global --add safe.directory /__w/musicoteca/musicoteca
          git config --global user.email "musicoteca@github.com"
          git config --global user.name "GitHub Actions"
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
          git add media-generation.json
          git add public/collection
          (git commit -m "[AUTO] Generating media files" && git push) || exit 0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  index-files:
    runs-on: ubuntu-latest
    needs: [generate-medias]
    permissions:
      contents: write
      packages: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          # By default checkout action checks out the repository at the commit that triggered the workflow.
          # `github.ref` holds the branch name or tag name that triggered the workflow,
          # so we can use it to checkout the last commit of the branch.
          ref: ${{ github.ref }}
      - name: Run upterm for debugging
        uses: lhotari/action-upterm@v1
      - name: Index collection
        run: |
          mv public/collection /tmp/collection
          npm ci
          npm run index-collection -- -i /tmp/collection -o public/collection
      - name: Commit and push files
        run: |
          git config --global --add safe.directory /__w/musicoteca/musicoteca
          git config --global user.email "musicoteca@github.com"
          git config --global user.name "GitHub Actions"
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
          git add public/collection
          (git commit -m "[AUTO] Generating index file" && git push) || exit 0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
