#
name: Generate medias from Musescore files

# Configures this workflow to run every time a change is pushed to the branch called `release`.
on:
  workflow_dispatch:

jobs:
  generate-medias:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: read
    container:
      image: ghcr.io/soprodecarnaval/musicoteca:main
      options: --user root --workdir /app
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Create generator file
        shell: sh
        run: |
          find public/collection/ -type f -name "*.mscz" | jq -R -s 'split("\n") | map(select(.!="") | sub(".mscz";"") | {"in":"\(.).mscz", "out": [[ "\(.)_",".svg"],[ "\(.)_",".midi"],"\(.).midi","\(.).metajson"]})' > media-generation.json
          head media-generation.json
      - name: Create media files
        shell: sh
        run: |
          xvfb-run /squashfs-root/AppRun -j media-generation.json
          find public/collection/ -type f -name "*.svg" -a -name "*.midi" | head
      - name: Commit and push files
        shell: sh
        run: |
          git config --global --add safe.directory /__w/musicoteca/musicoteca
          git config --global user.email "musicoteca@github.com"
          git config --global user.name "GitHub Actions"
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
          git add media-generation.json
          git add public/collection
          (git commit -m "[AUTO] Generating media files" && git push) || exit 0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  index-files:
    runs-on: ubuntu-latest
    needs: [generate-medias]
    permissions:
      contents: write
      packages: read
    container:
      image: node:18.18.2-alpine3.18
      options: --user root --workdir /app
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Index file
        run: |
          mv public/collection /collection
          npm run index-collection -- -i /collection -o public/collection
      - name: Commit and push files
        run: |
          git config --global --add safe.directory /__w/musicoteca/musicoteca
          git config --global user.email "musicoteca@github.com"
          git config --global user.name "GitHub Actions"
          git add public/collection
          git commit -m "[AUTO] Generating index file"
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}